export const queryKeys = {
    sessions: ['sessions'] as const,
    messengerConnections: ['messenger-connections'] as const,
    messengerCandidates: (provider: string) => ['messenger-candidates', provider] as const,
    externalConversations: ['external-conversations'] as const,
    externalMessages: (conversationId: string) => ['external-messages', conversationId] as const,
    externalParticipants: (conversationId: string) => ['external-participants', conversationId] as const,
    session: (sessionId: string) => ['session', sessionId] as const,
    messages: (sessionId: string) => ['messages', sessionId] as const,
    machines: ['machines'] as const,
    quotas: ['quotas'] as const,
    sqliteStorage: ['sqlite-storage'] as const,
    hubSettings: ['hub-settings'] as const,
    workspacePins: ['workspace-pins'] as const,
    usageSummary: (range: string, timeZone: string) => ['usage-summary', range, timeZone] as const,
    machineCodexModels: (machineId: string) => ['machine-codex-models', machineId] as const,
    machineAgentAvailability: (machineId: string) => ['machine-agent-availability', machineId] as const,
    sessionCodexModels: (sessionId: string) => ['session-codex-models', sessionId] as const,
    gitBranch: (scope: string) => ['git-branch', scope] as const,
    gitStatus: (sessionId: string) => ['git-status', sessionId] as const,
    gitDiff: (sessionId: string, comparison: string) => ['git-diff', sessionId, comparison] as const,
    gitComparison: (sessionId: string, scope: string) => ['git-comparison', sessionId, scope] as const,
    sessionFiles: (sessionId: string, query: string) => ['session-files', sessionId, query] as const,
    sessionDirectory: (sessionId: string, path: string) => ['session-directory', sessionId, path] as const,
    sessionFile: (sessionId: string, path: string) => ['session-file', sessionId, path] as const,
    gitFileDiff: (sessionId: string, path: string, staged?: boolean, comparison?: string) => [
        'git-file-diff',
        sessionId,
        path,
        comparison ?? (staged === true ? 'staged' : staged === false ? 'unstaged' : 'file')
    ] as const,
    slashCommands: (sessionId: string) => ['slash-commands', sessionId] as const,
    sessionCursorModels: (sessionId: string) => ['session-cursor-models', sessionId] as const,
    sessionCursorChatStore: (sessionId: string) => ['session-cursor-chat-store', sessionId] as const,
    sessionPiModels: (sessionId: string) => ['session-pi-models', sessionId] as const,
    machineCursorModels: (machineId: string) => ['machine-cursor-models', machineId] as const,
    sessionOpencodeModels: (sessionId: string) => ['session-opencode-models', sessionId] as const,
    sessionOpencodeReasoningEffortOptions: (sessionId: string) => ['session-opencode-reasoning-effort-options', sessionId] as const,
    machineOpencodeModelsForCwd: (machineId: string, cwd: string) => ['machine-opencode-models', machineId, cwd] as const,
    machineOpencodeModelVariants: (machineId: string) => ['machine-opencode-model-variants', machineId] as const,
    machineGrokModelsForCwd: (machineId: string, cwd: string) => ['machine-grok-models', machineId, cwd] as const,
    sessionGrokModels: (sessionId: string) => ['session-grok-models', sessionId] as const,
    sessionCopilotModels: (sessionId: string) => ['session-copilot-models', sessionId] as const,
    machineCopilotModelsForCwd: (machineId: string, cwd: string) => ['machine-copilot-models', machineId, cwd] as const,
    machineKimiModelsForCwd: (machineId: string, cwd: string) => ['machine-kimi-models', machineId, cwd] as const,
    sessionKimiModels: (sessionId: string) => ['session-kimi-models', sessionId] as const,
    sessionGrokReasoningEffortOptions: (sessionId: string) => ['session-grok-reasoning-effort-options', sessionId] as const,
    machineAgyModels: (machineId: string) => ['machine-agy-models', machineId] as const,
    machinePiModels: (machineId: string) => ['machine-pi-models', machineId] as const,
    skills: (sessionId: string) => ['skills', sessionId] as const,
    scratchlist: (sessionId: string) => ['scratchlist', sessionId] as const,
}
